package com.georgeme;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.georgeme.Restaurant;
import com.georgeme.User;

import com.georgeme.RestaurantDao;
import com.georgeme.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig restaurantDaoConfig;
    private final DaoConfig userDaoConfig;

    private final RestaurantDao restaurantDao;
    private final UserDao userDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        restaurantDaoConfig = daoConfigMap.get(RestaurantDao.class).clone();
        restaurantDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        restaurantDao = new RestaurantDao(restaurantDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Restaurant.class, restaurantDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        restaurantDaoConfig.getIdentityScope().clear();
        userDaoConfig.getIdentityScope().clear();
    }

    public RestaurantDao getRestaurantDao() {
        return restaurantDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
